import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
import { chromium } from 'playwright';
const types = {'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.woff2':'font/woff2'};
const server=createServer(async(req,res)=>{try {const path=decodeURIComponent(req.url.split('?')[0]);const file=join(process.cwd(),'dist',path==='/'?'index.html':path);const body=await readFile(file);res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream'});res.end(body);}catch {res.writeHead(404);res.end('Not found');}});
await new Promise(r=>server.listen(4174,r));
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const errors=[];
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('http://localhost:4174/',{waitUntil:'load'}); await page.waitForTimeout(3300);
 await page.screenshot({path:'reference/v2-desktop.png'});
 console.log('Desktop title:',await page.title());
 console.log('Desktop overflow:',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
 console.log('Hero font sizes:',await page.evaluate(()=>Object.fromEntries(['.hero-kicker','.hero-description','.hero-assurances','.brand-name small','.hero h1','.hero h2'].map(s=>[s,getComputedStyle(document.querySelector(s)).fontSize]))));
 await page.locator('#explore').scrollIntoViewIfNeeded(); await page.waitForTimeout(1100); await page.screenshot({path:'reference/v2-explore.png'});
 await page.locator('#kazakhstan').scrollIntoViewIfNeeded(); await page.waitForTimeout(1000); await page.screenshot({path:'reference/v2-map.png'});
 await page.locator('.map-region-buttons button').last().click(); await page.waitForFunction(()=>document.querySelector('.map-info-copy h3')?.textContent === 'Жетісу');
 console.log('Map selection:',await page.locator('.map-info-copy h3').innerText());
 await page.locator('.map-reset').click();await page.waitForFunction(()=>document.querySelector('.map-info-copy h3')?.textContent === 'Ұлы даланы бірге ашайық.');
 console.log('Map reset:',await page.locator('.map-info-copy h3').innerText());
 await page.locator('.hero-about').click();await page.waitForTimeout(400);
 console.log('About dialog:',await page.getByRole('dialog').count());
 await page.keyboard.press('Escape');await page.waitForTimeout(300);
 await page.locator('.category-card').first().click();await page.waitForTimeout(350);
 await page.locator('.lesson-list-item').first().click();await page.waitForTimeout(500);
 console.log('Lesson:',await page.locator('.lesson-panel h2').innerText());
 await page.screenshot({path:'reference/v2-lesson.png'});
 await page.locator('.lesson-actions .primary-button').click();await page.waitForTimeout(300);
 console.log('Progress storage:',await page.evaluate(()=>localStorage.getItem('qazaq-tili-progress-v1')));
 await page.keyboard.press('Escape');await page.waitForTimeout(400);
 await page.locator('.game-card').first().click();await page.waitForTimeout(400);
 console.log('Quiz question:',await page.locator('.question-title').innerText());
 await page.locator('.quiz-option').first().click(); await page.waitForTimeout(500);await page.screenshot({path:'reference/v2-quiz.png'});
 await page.locator('.game-next').click();await page.waitForTimeout(400);console.log('Question transition:',await page.locator('.game-progress-label').innerText());
 await page.keyboard.press('Escape');await page.waitForTimeout(300);
 await page.locator('.word-flip-target').click();await page.waitForTimeout(700);console.log('Word flipped:',await page.locator('.word-card').getAttribute('class'));
 await page.locator('.save-word').click();await page.waitForTimeout(200);
 await page.locator('.progress-button').click();await page.waitForTimeout(400);await page.screenshot({path:'reference/v2-progress.png'});await page.keyboard.press('Escape');await page.waitForTimeout(300);
 await page.locator('.language-button').click();console.log('Language:',await page.locator('h1').innerText());
 const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
 mobile.on('pageerror',e=>errors.push(e.message));
 await mobile.goto('http://localhost:4174/');await mobile.waitForTimeout(3300);await mobile.screenshot({path:'reference/v2-mobile.png',fullPage:true});
 console.log('Mobile overflow:',await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
 await mobile.locator('.mobile-menu-button').click();await mobile.waitForTimeout(350);await mobile.screenshot({path:'reference/v2-mobile-menu.png'});
 const small=await browser.newPage({viewport:{width:360,height:780},reducedMotion:'reduce'});
 await small.goto('http://localhost:4174/');await small.waitForTimeout(500);
 console.log('360 overflow:',await small.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
 console.log('Reduced motion:',await small.locator('html').getAttribute('class'));
 console.log('ERRORS',JSON.stringify(errors));
} finally {await browser.close();server.close();}
